config/routes.rb
Rails.application.routes.draw do
  get 'admin', to: 'admin#index'

  resources :looks do
    member do
      get :add_to, :remove_from
    end
  end
  resources :look_types
  resources :garments
  resources :garment_types
  devise_for :users
  get 'home/index'

  

  root 'home#index'

end

app/controllers/garment_types_controller.rb
class GarmentTypesController < ApplicationController
  #before_action :set_garment_type, only: [:show, :edit, :update, :destroy]

  # GET /garment_types
  # GET /garment_types.json
  def index
    @garment_types = GarmentType.all
  end

  # GET /garment_types/1
  # GET /garment_types/1.json
  def show
    @garment_type = GarmentType.find(params[:id])
  end

  # GET /garment_types/new
  def new
    @garment_type = GarmentType.new
  end

  # GET /garment_types/1/edit
  def edit
    @garment_type = GarmentType.find(params[:id])
  end

  # POST /garment_types
  # POST /garment_types.json
  def create
    @garment_type = GarmentType.new(garment_type_params)

    respond_to do |format|
      if @garment_type.save
        format.html { redirect_to @garment_type, notice: 'Garment type was successfully created.' }
        format.json { render :show, status: :created, location: @garment_type }
      else
        format.html { render :new }
        format.json { render json: @garment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /garment_types/1
  # PATCH/PUT /garment_types/1.json
  def update
    @garment_type = GarmentType.find(params[:id])
    respond_to do |format|
      if @garment_type.update(garment_type_params)
        format.html { redirect_to @garment_type, notice: 'Garment type was successfully updated.' }
        format.json { render :show, status: :ok, location: @garment_type }
      else
        format.html { render :edit }
        format.json { render json: @garment_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /garment_types/1
  # DELETE /garment_types/1.json
  def destroy
    @garment_type = GarmentType.find(params[:id])
    @garment_type.destroy
    respond_to do |format|
      format.html { redirect_to garment_types_url, notice: 'Garment type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #def set_garment_type
    #  @garment_type = GarmentType.find(params[:id])
    #end

    # Never trust parameters from the scary internet, only allow the white list through.
    def garment_type_params
      params.require(:garment_type).permit(:name, :icon)
    end
end

app/helpers/garment_types_helper.rb
module GarmentTypesHelper
end

app/views/garment_types/_form.html.erb
<%= simple_form_for(@garment_type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :icon %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/garment_types/edit.html.erb
<h1>Editing Garment Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @garment_type %> |
<%= link_to 'Back', garment_types_path %>

app/views/garment_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Garment Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Icon</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @garment_types.each do |garment_type| %>
      <tr>
        <td><%= garment_type.name %></td>
        <td><%= garment_type.icon %></td>
        <td><%= link_to 'Show', garment_type %></td>
        <td><%= link_to 'Edit', edit_garment_type_path(garment_type) %></td>
        <td><%= link_to 'Destroy', garment_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Garment type', new_garment_type_path %>

app/views/garment_types/new.html.erb
<h1>New Garment Type</h1>

<%= render 'form' %>

<%= link_to 'Back', garment_types_path %>

app/views/garment_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @garment_type.name %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @garment_type.icon %>
</p>

<%= link_to 'Edit', edit_garment_type_path(@garment_type) %> |
<%= link_to 'Back', garment_types_path %>