config/routes.rb
Rails.application.routes.draw do
  get 'admin', to: 'admin#index'

  resources :looks do
    member do
      get :add_to, :remove_from
    end
  end
  resources :look_types
  resources :garments
  resources :garment_types
  devise_for :users
  get 'home/index'

  

  root 'home#index'

end

app/models/look.rb
class Look < ActiveRecord::Base
  
  belongs_to :user
  has_many :look_garments
  has_many :garments, through: :look_garments
    has_many :look_type_joins
  has_many :look_types, through: :look_type_joins

  validates :name, presence: true
end

app/models/look_type.rb
class LookType < ActiveRecord::Base
	 has_many :look_type_joins
  has_many :looks, through: :look_type_joins
end

app/controllers/looks_controller.rb
class LooksController < ApplicationController
  before_action :set_look, only: [:add_to, :remove_from, :show, :edit, :update, :destroy]

  def add_to
    @garment = Garment.find(params[:garment])
    @look.garments << @garment
    redirect_to root_path(garment_type: @garment.garment_type.id)
  end

  def remove_from
    @garment = Garment.find(params[:garment])
    @look.garments.delete(@garment)
    redirect_to root_path(garment_type: @garment.garment_type.id)
  end


  # GET /looks
  # GET /looks.json
  def index
    @looks = Look.all
     @look_types = LookType.all.order(name: :asc)

  end

  # GET /looks/1
  # GET /looks/1.json
  def show
  end

  # GET /looks/new
  def new
    @look = Look.new
    @current_look = Look.find(params[:look])
  end

  # GET /looks/1/edit
  def edit
  end

  # POST /looks
  # POST /looks.json
  def create
    @look = Look.new(look_params)
    @look.user = current_user
    @copy_look = Look.find(params[:current_look])

    respond_to do |format|
      if @look.save
        @copy_look.garments.each do |garment|
          @look.garments << garment
        end
        format.html { redirect_to @look, notice: 'Look was successfully created.' }
        format.json { render :show, status: :created, location: @look }
      else
        format.html { render :new }
        format.json { render json: @look.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /looks/1
  # PATCH/PUT /looks/1.json
  def update
    respond_to do |format|
      if @look.update(look_params)
        format.html { redirect_to @look, notice: 'Look was successfully updated.' }
        format.json { render :show, status: :ok, location: @look }
      else
        format.html { render :edit }
        format.json { render json: @look.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /looks/1
  # DELETE /looks/1.json




  def destroy
    @look.destroy
    respond_to do |format|
      format.html { redirect_to looks_url, notice: 'Look was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_look
      @look = Look.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def look_params
      params.require(:look).permit(:name, :user_id, :current_look)
    end
end

app/helpers/looks_helper.rb
module LooksHelper
end

app/views/looks/_form.html.erb
<%= simple_form_for(@look) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, collection: LookType.order(name: :asc) %>
  </div>
  <%= text_field_tag(:current_look, params[:look]) %>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/looks/edit.html.erb
<h1>Editing Look</h1>

<%= render 'form' %>

<%= link_to 'Show', @look %> |
<%= link_to 'Back', looks_path %>

app/views/looks/index.html.erb
<div class="container bg-3 text-center"> 

  <div class="row">

    <div class="col-sm-3">
    <button type="button" class="btn btn-default">Choose the ocassion</button>
    <br><br>
    <div class="panel panel-default">
      <div class="panel-body">
  

     <% @look_types.each do |look_type| %>
      <%= link_to look_type.name, looks_path, class: 'btn btn-default btn-block' %>
     <% end %>
</div></div>
    </div>
    
    <div class="col-sm-6">
    
      <div class="panel panel-default">
        <div class="panel-body">
          <div style="height: 600px;"></div>
        </div>
      </div>
    </div>



   
      
    </div>
  </div>
</div>
</div>

app/views/looks/new.html.erb
<h1>Save your look</h1>

<div class="row">
<div class="col-md-4">
<div class="panel panel-default">
<div class="panel-body">

<%= render 'form' %>

</div>
</div>
</div>
<div class="col-md-4">
<div class="panel panel-default">
<div class="panel-body">
      <div class ="row">
            <% @current_look.garments.each do |garment| %>
	            <div class="col-sm-4">
	             
	              <%= image_tag garment.photo, class: 'img-responsive'%> <%= link_to "<i class='fa fa-times'></i>".html_safe, remove_from_look_path(@current_look, garment: garment.id) %>
				</div>
            <% end %> 
           
        </div>
       </div>
      </div>
     </div>
     </div>


<%= link_to 'Back', root_path %>

app/views/looks/old_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Looks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @looks.each do |look| %>
      <tr>
        <td><%= look.name %></td>
        <td><%= look.user %></td>
        <td><%= link_to 'Show', look %></td>
        <td><%= link_to 'Edit', edit_look_path(look) %></td>
        <td><%= link_to 'Destroy', look, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Look', new_look_path %>

app/views/looks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @look.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @look.user %>
</p>

<%= link_to 'Edit', edit_look_path(@look) %> |
<%= link_to 'Back', looks_path %>

<div class="panel panel-default">
<div class="panel-body">
      <div class ="row">
            <% @look.garments.each do |garment| %>
	            <div class="col-sm-4">
	             
	              <%= image_tag garment.photo, class: 'img-responsive'%> <%= link_to "<i class='fa fa-times'></i>".html_safe, remove_from_look_path(@look, garment: garment.id) %>
				</div>
            <% end %> 
           
        </div>
       </div>
      </div>