config/routes.rb
Rails.application.routes.draw do
  get 'admin', to: 'admin#index'

  resources :looks do
    member do
      get :add_to, :remove_from
    end
  end
  resources :look_types
  resources :garments
  resources :garment_types
  devise_for :users
  get 'home/index'

  

  root 'home#index'

end

app/controllers/look_types_controller.rb
class LookTypesController < ApplicationController
  before_action :set_look_type, only: [:show, :edit, :update, :destroy]

  # GET /look_types
  # GET /look_types.json
  def index
    @look_types = LookType.all
  end

  # GET /look_types/1
  # GET /look_types/1.json
  def show
  end

  # GET /look_types/new
  def new
    @look_type = LookType.new
  end

  # GET /look_types/1/edit
  def edit
  end

  # POST /look_types
  # POST /look_types.json
  def create
    @look_type = LookType.new(look_type_params)

    respond_to do |format|
      if @look_type.save
        format.html { redirect_to @look_type, notice: 'Look type was successfully created.' }
        format.json { render :show, status: :created, location: @look_type }
      else
        format.html { render :new }
        format.json { render json: @look_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /look_types/1
  # PATCH/PUT /look_types/1.json
  def update
    respond_to do |format|
      if @look_type.update(look_type_params)
        format.html { redirect_to @look_type, notice: 'Look type was successfully updated.' }
        format.json { render :show, status: :ok, location: @look_type }
      else
        format.html { render :edit }
        format.json { render json: @look_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /look_types/1
  # DELETE /look_types/1.json
  def destroy
    @look_type.destroy
    respond_to do |format|
      format.html { redirect_to look_types_url, notice: 'Look type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_look_type
      @look_type = LookType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def look_type_params
      params.require(:look_type).permit(:name)
    end
end

app/helpers/look_types_helper.rb
module LookTypesHelper
end

app/views/look_types/_form.html.erb
<%= simple_form_for(@look_type) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/look_types/edit.html.erb
<h1>Editing Look Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @look_type %> |
<%= link_to 'Back', look_types_path %>

app/views/look_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Look Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @look_types.each do |look_type| %>
      <tr>
        <td><%= look_type.name %></td>
        <td><%= link_to 'Show', look_type %></td>
        <td><%= link_to 'Edit', edit_look_type_path(look_type) %></td>
        <td><%= link_to 'Destroy', look_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Look type', new_look_type_path %>

app/views/look_types/new.html.erb
<h1>New Look Type</h1>

<%= render 'form' %>

<%= link_to 'Back', look_types_path %>

app/views/look_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @look_type.name %>
</p>

<%= link_to 'Edit', edit_look_type_path(@look_type) %> |
<%= link_to 'Back', look_types_path %>